name: CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-20.04
          - windows-2019

    runs-on: ${{ matrix.os }}

    env:
      DOTNET_NOLOGO: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: NuGet package cache
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore CI.slnf --locked-mode

    - name: Build
      run: dotnet build CI.slnf --configuration Release --no-restore

    - name: Test (net6.0)
      run: dotnet test CI.slnf --configuration Release --no-build --framework net6.0

    - name: Test (net48/Windows)
      run: dotnet test CI.slnf --configuration Release --no-build --framework net48
      if: ${{ runner.os == 'Windows' }}

    - name: Uploading nuget packages as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NuGet Packages
        path: '**/*.nupkg'
        if-no-files-found: error
      if: ${{ runner.os == 'Linux' }}
